### ISSUE TITLE
Allow configurable ConnectionOptions

### ISSUE THREAD

**Issue by qwbarch** [moesenle/servant-websockets#11]
Would it be possible for ``ConnectionOptions`` to be passed in?
Not sure how this would work since it's hidden behind a ``HasServer`` instance

Edit: Nevermind, I realized this is configurable via a ``PendingConnection``.

**Comment by flip111** [comment]
@qwbarch How did you set the `ConnectionOptions` via the `PendingConnection`?

**Comment by qwbarch** [comment]
> @qwbarch How did you set the `ConnectionOptions` via the `PendingConnection`?

``PendingConnection`` is a record that holds ``ConnectionOptions``, so you just need to update your record (before passing it to ``acceptConnection`` or whatever the function's called)

**Comment by flip111** [comment]
Good advice, thanks @qwbarch !

https://hackage.haskell.org/package/websockets-0.13.0.0/docs/Network-WebSockets.html#v:acceptRequest
